### ISSUE TITLE
Make a better keyboard layout for the default keyboard

### ISSUE THREAD

**Issue by GoogleCodeExporter** [michaelbarlow7/dungeon-crawl-android#15]
```
Forum member 'eeviac' wants a better keyboard. Should just be a matter of 
changing the xml layouts, but there might be some trickiness regarding metakeys.

Attached is the proposed keyboard layout.
```

Original issue reported on code.google.com by `michaelbarlow7` on 8 Sep 2012 at 5:57

Attachments:
* [keyboard.jpg](https://storage.googleapis.com/google-code-attachments/dungeon-crawl-android/issue-15/comment-0/keyboard.jpg)

**Comment by michaelbarlow7** [comment]
You can now customise the keyboard.
