### ISSUE TITLE
support unicode character set display 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [michaelbarlow7/dungeon-crawl-android#50]
```
Currently the character set option seems to be ignored. It would be great if 
the unicode character option would be recognized and display adjusted as per 
the main crawl standard. 

```

Original issue reported on code.google.com by `kristoff...@gmail.com` on 12 Oct 2014 at 11:37

**Comment by michaelbarlow7** [comment]
I noticed that the wide unicode characters were just being cast to 8-bit chars, so they'd lose their wideness. They're now 16-bits, which isn't quite 4 bytes but should be ok. Haven't tested this out though. Will close this now and reopen another if needs be.
