### ISSUE TITLE
Merge/update current crawl release version code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [michaelbarlow7/dungeon-crawl-android#51]
```
This code is based on main Crawl code v 0.14, though the current release 
version of main Crawl is at v 15.1.
```

Original issue reported on code.google.com by `kristoff...@gmail.com` on 12 Oct 2014 at 11:40

**Comment by kribjo** [comment]
I would love to see "Unofficial Tiles Android DCSS" up to date with main DCSS, v0.16.1 released today.

**Comment by michaelbarlow7** [comment]
Working on it!

**Comment by kribjo** [comment]
Thanks, no stress-inducement intended - just so you know that there is an
appreciative audience! :D

**Comment by michaelbarlow7** [comment]
All good! 0.16.1 is up in Google Play now. Enjoy!
