### ISSUE TITLE
Game quits when picking up $ in Spider's Nest

### ISSUE THREAD

**Issue by michaelbarlow7** [michaelbarlow7/dungeon-crawl-android#56]
Posted via email by 이병관.

If you pick up money (or runes) in Spider's Nest, Shoals, or Slime Pit, the game exits.

I can only reproduce this sometimes using a Nexus 5 ARMv7 emulator running Lollipop, though I've managed to produce a save that causes the crash 100% of the time.

The crash occurs at items.cc:1584, specifically when trying to find "needs_autopickup" in the hashmap, and it's a segmentation fault. Not sure exactly what's causing this yet, but will try and investigate further using gdb.

**Comment by abienz** [comment]
This has been noted with the other version of DCSS for Android, it's to do with ARM processors, the solution to this issue can be found here: https://crawl.develz.org/mantis/view.php?id=9630

**Comment by michaelbarlow7** [comment]
Wow, thanks internet! Specifically abienz! I was tearing my hair out trying to track down this error.

Thank you so much for this, I'll add signed chars and check that it goes away.

**Comment by michaelbarlow7** [comment]
Yep, it does. This will be fixed in the next release.
