### ISSUE TITLE
Strange behaviour with mobs and stairs

### ISSUE THREAD

**Issue by michaelbarlow7** [michaelbarlow7/dungeon-crawl-android#57]
According to Matty O'Toole on Google Play:

"If you go up/down stairs with mobs next to you they don't follow you up/down the stairs. This makes avoiding mobs too easy and kind of ruins the difficulty of the game. Summoned allies will follow you up/down stairs but will be placed in a random location on the level rather than next to you. Mobs will also occasionally get stuck in walls, sometimes killing you instantly despite not being on the map"

**Comment by unforgettableid** [comment]
I, too, am reliably able to reproduce this bug.

**Comment by unforgettableid** [comment]
I spoke with _miek on IRC today.  He has also experienced the bug, but has no idea what causes it.

**Comment by Nistenf** [comment]
I can also reproduce this bug

**Comment by simex909** [comment]
I am experiencing the same thing. Running lollipop 5.1. Is it possible to download previous builds before the bug was introduced?

**Comment by unforgettableid** [comment]
Was there ever any old version of console DCSS for Android which didn't have this bug?

**Comment by simex909** [comment]
Yes. I'm not sure which version, but I had one that was sometime after they introduced felids and octopodes, but before they got rid of weight. It did not have the stair bug.

**Comment by michaelbarlow7** [comment]
Found the issue. This Android build doesn't use the same Makefile, so the ASSERTS flag wasn't being switched on. There were a couple of methods regarding new creature placement that were wrapped in ASSERT preprocessor directives. Since ASSERTs weren't switched on, these methods were essentially taken out by the compiler.
This shouldn't happen, and is technically a minor bug in the crawl code, but for now I need to explicitly turn on ASSERTS. This will be fixed in the next build.

**Comment by kribjo** [comment]
Hooray! Mobs-Players 1-0! :)

**Comment by michaelbarlow7** [comment]
Gonna do a pull request on the official code later, but for the app, this is closed.
