### ISSUE TITLE
"Preferences > Hardware key mapping > Symbols" can't map a key to "backquote"

### ISSUE THREAD

**Issue by unforgettableid** [michaelbarlow7/dungeon-crawl-android#59]
The backquote character (the ` character, also known as the backtick character) is useful in Crawl.  It lets you repeat the last action taken.  So it makes it easier to cast Magic Dart fifteen times in a row, or to eat ten fruits in a row, or to do other repetitive actions.

I'm using a Samsung Galaxy S Relay cellphone with a slide-out hardware keyboard.  I've also installed a software keyboard app, named SwiftKey.  I've found that SwiftKey does let me send the backquote character, but the phone's built-in hardware keyboard doesn't.

`Preferences > Hardware key mapping > Symbols` doesn't let me a spare hardware keyboard key to send a backquote when pressed.  "Single quote" and "double quote" are on the list of available symbols, but "backquote" isn't.

It would be most excellent if you could please add "backquote" to the list.

**Comment by unforgettableid** [comment]
P.S.  Thank you very much for writing and maintaining dungeon-crawl-android.

**Comment by michaelbarlow7** [comment]
Added in 0.19.0
