### ISSUE TITLE
Black screen in landscape mode

### ISSUE THREAD

**Issue by sbaro** [michaelbarlow7/dungeon-crawl-android#63]
Hi,
I installed DCSS android on a Samsung Galaxy Note 4 (Android 5.1.1). Each time the software switches to landscape mode (either with the sensor orientation, or because the option is "landscape") the screen goes completely black (but I don't know if it is "black" or if the screen is switched off). It stays so until I go back to the android main screen. If I switch back to DCSS, the screen goes and stay black again (even if I tilt the phone if in sensor mode). The only way to get DCSS again is to kill the app.

**Comment by n0manarmy** [comment]
I saw this with my nexus 6 on marshmallow. As a temp fix I set the orientation to my fixed preference in the menu. I can look at this and see what's going on.

**Comment by michaelbarlow7** [comment]
I'm able to reproduce this in the emulator running Marshmallow emulating a nexus 6. Had a quick debug sesh tonight but couldn't work out where the problem was. Will look further.

**Comment by michaelbarlow7** [comment]
Fixed. There was a method which increased the font size until it fit the width of the screen,but the max font size was being hit on the Nexus 6 which caused the loop to spin indefinitely.

**Comment by sbaro** [comment]
Good job! It works fine. It's nice because landscape makes it much more easy to play on a phone. Thanks again for the good work you do with this game!!!
