### ISSUE TITLE
GCC is deprecated, move to clang

### ISSUE THREAD

**Issue by michaelbarlow7** [michaelbarlow7/dungeon-crawl-android#64]
https://android.googlesource.com/platform/ndk.git/+/master/CHANGELOG.md

Not actually sure how this relates to us, especially since we're using the CrystaX toolchain, but it's probably worth investigating.

**Comment by n0manarmy** [comment]
This project should be good. I have other projects that will not be :sad:

**Comment by michaelbarlow7** [comment]
I think we're using this now
