### ISSUE TITLE
Upload to F-Droid

### ISSUE THREAD

**Issue by michaelbarlow7** [michaelbarlow7/dungeon-crawl-android#74]
Someone suggested this at one stage and it seems like a good idea.

**Comment by michaelbarlow7** [comment]
Tried implementing this myself but I'm not quite sure how to get it to use CrystaX's toolchain, and also recursively clone to include the subdirectories.

**Comment by michaelbarlow7** [comment]
Posted this on the forum: https://f-droid.org/forums/topic/dungeon-crawl-stone-soup-ascii/

**Comment by michaelbarlow7** [comment]
We're no longer using the CrystaX toolchain so this looks more possible, possibly.

**Comment by michaelbarlow7** [comment]
Looks like it supports submodules

https://f-droid.org/docs/Build_Metadata_Reference/#build_submodules

Will need to run setup.sh before running the build but this should be doable.

**Comment by michaelbarlow7** [comment]
The prebuild section should be able to do this

**Comment by michaelbarlow7** [comment]
Have followed the instructions here (https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/), but am getting a 500 when trying to create the merge request at https://gitlab.com/fdroid/fdroiddata/-/merge_requests .

I also haven't done anything to sign the package so I'm not sure I've done it correctly, but I've followed the instructions so I guess we'll see.

**Comment by michaelbarlow7** [comment]
Turns out I hadn't updated the fork since I first tried this in 2016 so it's likely the merge request was timing out due to the number of commits since then. Will try updating my fork and try again.

**Comment by michaelbarlow7** [comment]
I've submitted the merge request. I suppose I could try and make reproducible builds but not sure if it's worth the trouble?

https://f-droid.org/docs/Reproducible_Builds/

**Comment by joeljpa** [comment]
> We're no longer using the CrystaX toolchain so this looks more possible, possibly.

Thanks a lot for your dedication to this project, for more than seven years. Using the standard NDK over CrystaX no doubt was a big task and extends this project's life. Possibly due to it, I remember struggling to compile it years ago when I used to have more time on my hands.

> I've submitted the merge request. I suppose I could try and make reproducible builds but not sure if it's worth the trouble?
> 
> https://f-droid.org/docs/Reproducible_Builds/

You've been trying to do this since 2016 and if still no luck in completion, maybe it's not? Anyone can easily download the apks from the releases listed there.

**Comment by michaelbarlow7** [comment]
> > We're no longer using the CrystaX toolchain so this looks more possible, possibly.
> 
> Thanks a lot for your dedication to this project, for more than seven years. Using the standard NDK over CrystaX no doubt was a big task and extends this project's life. Possibly due to it, I remember struggling to compile it years ago when I used to have more time on my hands.

Thanks for the nice words! Sorry I've been a bit slack with this repo, took a break from it and coding in general. Good to be back though, and it's nice that people are still getting some enjoyment with it :).
> 
> > I've submitted the merge request. I suppose I could try and make reproducible builds but not sure if it's worth the trouble?
> > https://f-droid.org/docs/Reproducible_Builds/
> 
> You've been trying to do this since 2016 and if still no luck in completion, maybe it's not? Anyone can easily download the apks from the releases listed there.

Well I tried in 2016 but the CrystaX toolchain made it hard so I gave up. Thankfully it was way easier this time, one of the contributors has been super helpful.
