### ISSUE TITLE
add older versions to releases

### ISSUE THREAD

**Issue by Dracunos** [michaelbarlow7/dungeon-crawl-android#76]
Playing older versions is pretty big in dcss compared to many other games, all the online servers even include much older versions. I'd like to see a repository of older versions of this great application (personally I play 17 atm) if it doesn't exist. Github or eventually fdroid seems like the natural place for them.

**Comment by Dracunos** [comment]
I badly need some experience with compiling android apps with gradle, so I'd be willing to work on it. I can also simply pull apks for 14 and 17 from titanium backup but not sure if that would be sufficient, I think I'd rather compile them.

Would this be a huge headache to do, or has not much changed? I might need a little bit of guidance on this if possible, but I'll try working on it on my own if you think it's reasonable to do.

**Comment by michaelbarlow7** [comment]
Tbh it's kind of annoying to compile the game for older versions. There's a bunch of steps involved, and some of the older versions rely on older versions of the CrystaX NDK toolchain, the version-numbers of which I can't remember.

That said, I can download the previous APKs from Google Play. I'd just need a decent place to put them. I'm open to recommendations.

I actually had all the released APKs publicly posted on Google Code, back when this project was hosted there.

**Comment by Dracunos** [comment]
Google Play keeps old releases? They just don't let the users actually access them?

I know FDroid keeps them all, and actually allows you to choose which version you want to install through their app. But I'm not sure if you can manually add older releases. Are there complications with adding older releases to the github releases?

Outside of FDroid and Github, what kind of solution are you thinking? Like simply hosting it on someone's website and linking it in the Github readme or something simple like that?

**Comment by michaelbarlow7** [comment]
Yeah, I can access the old releases because I'm the publisher, but they're not public.

I've tried uploading to FDroid but the build process for this app is a little bit more complicated than most. The issue for tracking this is here: https://github.com/michaelbarlow7/dungeon-crawl-android/issues/74.

I'm not sure what you mean by "adding older releases to github releases".

Yeah I'd basically be looking at a place for uploading the APKs. I'd want it to be fairly simple since I'd have to upload a new APK with each release. Maybe a dropbox would be fine?

**Comment by Dracunos** [comment]
I'm admittedly not that experienced with this stuff, so I don't fully understand the limitations or intended purpose, but you can upload files right into your github releases.

https://github.com/blog/1547-release-your-software 
It does say it's made for placing compiled executables
> You can also attach binary assets (such as compiled executables, minified scripts, documentation) to a release. Once published, the release details and assets are available to anyone that can view the repository.

I did it on my fork ( https://github.com/Dracunos/gnollcrawl/releases/tag/0.19-GnollCrawlA ) so someone could play it offline.

**Comment by michaelbarlow7** [comment]
Oh sweet, not sure how I missed that. I'll have to spend the time to go back and tag the release commits, and then attach the APKs, but I'm happy to do that at some point.

Thanks for raising the issue and suggesting solutions :)

**Comment by Dracunos** [comment]
That's nothing.. Thank you for making a really great game actually functional on android! I've put so many hours into the android ascii app, I think I've been playing off and on since 0.14.

**Comment by michaelbarlow7** [comment]
Dawww such kind words! I'm glad you like it. People like you keep me motivated to maintain this app xD

**Comment by Maxmanishe** [comment]
Hello Guys, Where Can I found the 0.14 Version of Soup with unofficial port by "michaelbarlow7"
Thanks you in advice

**Comment by michaelbarlow7** [comment]
Hey Maxmanishe, I still need to go through and upload the APKs for the corresponding releases. Looks like there's a bit more demand for this so hopefully I'll find some time this week :).

I'll post a link to 0.14 here once it's done.

**Comment by michaelbarlow7** [comment]
Alright, I've gone through and tagged all the releases to the best of my ability (commits may be slightly off). I've uploaded the corresponding APKs as they are in Google Play. The only one missing is `0.17.0` as the APK seems to be corrupted for some reason, but you'll probably want 0.17.1 anyway.

You can find the releases here: https://github.com/michaelbarlow7/dungeon-crawl-android/releases

@Maxmanishe, 0.14.0 can be found here: https://github.com/michaelbarlow7/dungeon-crawl-android/releases/tag/0.14.0

Enjoy!
