### ISSUE TITLE
Update to 0.21.0?

### ISSUE THREAD

**Issue by ddekok** [michaelbarlow7/dungeon-crawl-android#79]
I'd like to play with more gnolls, and less wands.

Pulled the source to try to do this myself, but having issue with the submodule (and getting a handle on the whole android toolchain)

Thanks for everything.

**Comment by thurber** [comment]
Hi @ddekok, I also wanted more gnolls and less food variety, so i've managed to build an APK from the master branch of crawl, corresponding to approximately version 0.22.0-a0. You can find it in my repo at https://github.com/thurber/androidSoup (requires manual install).

Thanks @michaelbarlow7 for your implementation and documentation!

**Comment by michaelbarlow7** [comment]
Closing this, since it's now up to 0.21.1 :)
