### ISSUE TITLE
Crawl keyboard doesn't change from initial layout when pressing shift or ctrl

### ISSUE THREAD

**Issue by seancamden** [michaelbarlow7/dungeon-crawl-android#83]
This is on an LG G6 running Android version 9 (not rooted or anything) using the crawl keyboard. Layout switching keys (shift, num, ctrl) still work, but the display doesn't change, forcing one to guess which key is where. As you can probably imagine, this introduces a whole new level of challenge to the game :-P

To reproduce: (start game), press the shift key. Notice: blue underline appears beneath up arrow, but see no other changes. Keys appear to still be all lower-case, but when you press them you get upper-case behavior. Same thing happens after pressing the numeric key or the ctrl key: no change visible, but if you can remember where the keys are you can click them and they work.

Thanks for all the work you've done! 

Edited to add: 0.24.0a

**Comment by sidav** [comment]
Does this reproduce in 0.23.2?

**Comment by seancamden** [comment]
Is there a way to install an older version without rooting my phone?

**Comment by michaelbarlow7** [comment]
Hi Sean!

I've just fixed this in 0.24.0b. Google changed the way some of the underlying code works for drawing views, which caused a crash in 0.24.0 and then weird behaviour in 0.24.0a. 

Sorry about that! Not the best idea to make a release around Christmas time when I have limited time to make critical fixes!

For future reference though, you can download older releases here https://github.com/michaelbarlow7/dungeon-crawl-android/releases
