### ISSUE TITLE
Exits immediately after showing "start screen"

### ISSUE THREAD

**Issue by kribjo** [michaelbarlow7/dungeon-crawl-android#88]
Version 0.29.1

Pixel 6 Pro, latest Android 13

When I start the game it shows the "start screen" ending with the "happy crawling" text and also the keyboard att the bottom. After a fraction of a second it closes down without any interaction.

**Comment by michaelbarlow7** [comment]
Hmmm, looks like there's some sort of string checking thing that the new clang compiler seems to be using. Will look into it.

**Comment by michaelbarlow7** [comment]
Fixed this in 0.29.1a . Compiling with clang in the latest official NDK runs some sort of FORTIFY checks, which the lua submodule seems to fail at runtime. Disabling the checks in Android.mk seems to fix this.

**Comment by kribjo** [comment]
I can confirm that this is fixed for me in 0.29.1a. Thanks!
